# Reglas de alertas para Bingo La Perla

groups:
  - name: bingo-application
    rules:
      # Alerta por alta latencia en el backend
      - alert: HighLatency
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 1
        for: 2m
        labels:
          severity: warning
          service: bingo-backend
        annotations:
          summary: "Alta latencia detectada en {{ $labels.instance }}"
          description: "La latencia del percentil 95 es {{ $value }}s, superior al umbral de 1s."

      # Alerta por alto rate de errores
      - alert: HighErrorRate
        expr: rate(http_requests_total{status=~"5.."}[5m]) / rate(http_requests_total[5m]) > 0.05
        for: 5m
        labels:
          severity: critical
          service: bingo-backend
        annotations:
          summary: "Alto rate de errores en {{ $labels.instance }}"
          description: "El rate de errores 5XX es {{ $value | humanizePercentage }}, superior al 5%."

      # Alerta por servicio caído
      - alert: ServiceDown
        expr: up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Servicio {{ $labels.job }} está caído"
          description: "El servicio {{ $labels.job }} en {{ $labels.instance }} no responde hace {{ $value }}."

      # Alerta por alto uso de CPU
      - alert: HighCPUUsage
        expr: 100 - (avg by(instance) (rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Alto uso de CPU en {{ $labels.instance }}"
          description: "El uso de CPU es {{ $value }}%, superior al 80%."

      # Alerta por alto uso de memoria
      - alert: HighMemoryUsage
        expr: (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100 > 85
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Alto uso de memoria en {{ $labels.instance }}"
          description: "El uso de memoria es {{ $value }}%, superior al 85%."

      # Alerta por poco espacio en disco
      - alert: LowDiskSpace
        expr: (1 - (node_filesystem_avail_bytes{fstype!="tmpfs"} / node_filesystem_size_bytes{fstype!="tmpfs"})) * 100 > 90
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Poco espacio en disco en {{ $labels.instance }}"
          description: "El disco {{ $labels.mountpoint }} está al {{ $value }}% de capacidad."

  - name: bingo-database
    rules:
      # Alerta por muchas conexiones a PostgreSQL
      - alert: PostgreSQLTooManyConnections
        expr: sum(pg_stat_activity_count) by (instance) > 150
        for: 2m
        labels:
          severity: warning
          service: postgresql
        annotations:
          summary: "Muchas conexiones activas en PostgreSQL"
          description: "PostgreSQL tiene {{ $value }} conexiones activas, superior a 150."

      # Alerta por queries lentas en PostgreSQL
      - alert: PostgreSQLSlowQueries
        expr: avg(rate(pg_stat_activity_max_tx_duration[5m])) by (instance) > 60
        for: 5m
        labels:
          severity: warning
          service: postgresql
        annotations:
          summary: "Queries lentas detectadas en PostgreSQL"
          description: "PostgreSQL tiene queries con duración promedio de {{ $value }}s."

      # Alerta por baja cache hit ratio
      - alert: PostgreSQLLowCacheHitRatio
        expr: avg(rate(pg_stat_database_blks_hit[5m]) / (rate(pg_stat_database_blks_hit[5m]) + rate(pg_stat_database_blks_read[5m]))) by (instance) < 0.9
        for: 5m
        labels:
          severity: warning
          service: postgresql
        annotations:
          summary: "Baja cache hit ratio en PostgreSQL"
          description: "Cache hit ratio es {{ $value | humanizePercentage }}, inferior al 90%."

      # Alerta por Redis desconectado
      - alert: RedisDown
        expr: redis_up == 0
        for: 1m
        labels:
          severity: critical
          service: redis
        annotations:
          summary: "Redis está desconectado"
          description: "Redis no responde en {{ $labels.instance }}."

      # Alerta por alta memoria en Redis
      - alert: RedisHighMemoryUsage
        expr: redis_memory_used_bytes / redis_memory_max_bytes > 0.9
        for: 5m
        labels:
          severity: warning
          service: redis
        annotations:
          summary: "Alto uso de memoria en Redis"
          description: "Redis está usando {{ $value | humanizePercentage }} de memoria disponible."

  - name: bingo-websocket
    rules:
      # Alerta por muchas conexiones WebSocket
      - alert: HighWebSocketConnections
        expr: socket_io_connected_clients > 1000
        for: 2m
        labels:
          severity: warning
          service: websocket
        annotations:
          summary: "Muchas conexiones WebSocket activas"
          description: "Hay {{ $value }} conexiones WebSocket activas, superior a 1000."

      # Alerta por errores en WebSocket
      - alert: WebSocketErrors
        expr: rate(socket_io_errors_total[5m]) > 10
        for: 2m
        labels:
          severity: warning
          service: websocket
        annotations:
          summary: "Errores frecuentes en WebSocket"
          description: "Rate de errores WebSocket: {{ $value }} errores/segundo."

  - name: bingo-business
    rules:
      # Alerta por muchos usuarios simultáneos en juego
      - alert: HighConcurrentPlayers
        expr: active_game_players > 500
        for: 1m
        labels:
          severity: info
          service: bingo-game
        annotations:
          summary: "Alto número de jugadores simultáneos"
          description: "Hay {{ $value }} jugadores activos en juegos simultáneos."

      # Alerta por juego sin actividad
      - alert: GameStalled
        expr: increase(game_balls_drawn_total[10m]) == 0 and game_status == 2
        for: 5m
        labels:
          severity: warning
          service: bingo-game
        annotations:
          summary: "Juego sin actividad detectado"
          description: "El juego {{ $labels.game_id }} no ha tenido actividad en 10 minutos."

      # Alerta por fallas en pagos
      - alert: PaymentFailures
        expr: rate(payment_failures_total[5m]) > 0.1
        for: 2m
        labels:
          severity: critical
          service: payments
        annotations:
          summary: "Fallas frecuentes en pagos"
          description: "Rate de fallas en pagos: {{ $value }} fallas/segundo."