# Configuración de Prometheus para Bingo La Perla

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'bingo-production'
    environment: 'production'

# Reglas de alertas
rule_files:
  - "/etc/prometheus/rules/*.yml"

# Configuración de AlertManager
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Trabajos de scraping
scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s

  # Node Exporter - Métricas del sistema
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s
    metrics_path: /metrics

  # Backend Application
  - job_name: 'bingo-backend'
    static_configs:
      - targets: ['backend:3001']
    scrape_interval: 10s
    metrics_path: /metrics
    scheme: http

  # Frontend Application (si expone métricas)
  - job_name: 'bingo-frontend'
    static_configs:
      - targets: ['frontend:3000']
    scrape_interval: 30s
    metrics_path: /metrics
    scheme: http

  # PostgreSQL Exporter
  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 30s

  # Redis Exporter
  - job_name: 'redis-exporter'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 30s

  # Nginx Exporter
  - job_name: 'nginx-exporter'
    static_configs:
      - targets: ['nginx-exporter:9113']
    scrape_interval: 30s

  # cAdvisor - Métricas de contenedores
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 30s

  # Blackbox Exporter - Health checks
  - job_name: 'blackbox-http'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - https://bingolaperla.com
        - https://api.bingolaperla.com/health
        - http://frontend:3000/health
        - http://backend:3001/health
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  # WebSocket Health Check
  - job_name: 'blackbox-websocket'
    metrics_path: /probe
    params:
      module: [websocket]
    static_configs:
      - targets:
        - wss://api.bingolaperla.com/socket.io/
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  # Docker containers metrics
  - job_name: 'docker-containers'
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 30s
    relabel_configs:
      - source_labels: [__meta_docker_container_label_com_docker_compose_service]
        target_label: service
      - source_labels: [__meta_docker_container_name]
        target_label: container